Version: 0.2

Variables:
    CACHECONTROL: 
    S3_BUCKET: “{{s3_bucket_sa-east-1}}”
    BUILD_FOLDER: “dist”
Phases:
  Install:
    Runtime-version:
      packageJSON
commands:
  - echo installing source NPM dependencies…
  - npm install
  - npm install -g@startbootstrap/cli
build:
  commands:
    - echo Build started on `date`
    - mvn install
artifacts:
files:
- ‘**/*’
base-directory: ‘dist’
discard-paths: yes
