versio: 0.2
phases:
  instal:
    runtime-version:
    nodejs: 12
  build:
  commands:
    - echo "Installing dependencies.."
    - npm install
    - echo "Unit testing.."
    - npm test
    - echo "building.."
    - npm build
artifacts:
  base-directory: build
  files:
    - '**/*'