version: 0.2
phases:
  install:
    runtime-version:
    nodejs: 12
  build:
    commands:
    - echo "Installing dependencies.."
    - npm install
    - echo "Unit testing.."
    - npm test
    - echo "building.."
    - npm build
build:
  commands:
    - echo Build started on `date`
    - mvn install
artifacts:
  files:
  - '**/*'
  base-directory: 'dist'
  discard-paths: yes
