Version: 0.2

Env:
Variables:
    CACHECONTROL: 
    S3_BUCKET: “{{s3_bucket_url}}”
    BUILD_FOLDER: “dist”
Phases:
  Install:
    Runtime-version:
      Nodejs:14
commands:
  - echo installing source NPM dependencies…
  - npm install
  - npm install -g@startbootstrap/cli
build:
  commands:
   -	echo Build started
   -	nybuild
artifacts:
files:
- ‘**/*’
base-directory: ‘dist’
discard-paths: yes
